# coding=UTF-8
ENCODING = 'UTF-8'

DEFAULT_DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S'
DEFAULT_DATE_FORMAT = '%Y-%m-%d'

MOBILE_X_HEADER_EMAIL = 'X-Kujonmobiemail'
MOBILE_X_HEADER_TOKEN = 'X-Kujonmobitoken'
MOBILE_X_HEADER_REFRESH = 'X-Kujonrefresh'
EVENT_X_HUB_SIGNATURE = 'X-Hub-Signature'

SECONDS_1MONTH = 2592000
SECONDS_2MONTHS = 5184000
SECONDS_YEAR = 31104000
SECONDS_DAY = 86400
SECONDS_1WEEK = 604800
SECONDS_2WEEKS = 1209600
SECONDS_HOUR = 3600

MAX_HTTP_CLIENTS = 100

HTTP_CONNECT_TIMEOUT = 50
HTTP_REQUEST_TIMEOUT = 50
HTTP_VALIDATE_CERT = True

SECONDS_REMOVE_ON_REFRESH = 15

APPLICATION_DB = 'application_db'
APPLICATION_CONFIG = 'application_config'
APPLICATION_AES = 'application_aes'
APPLICATION_FS = 'application_fs'
