# coding=UTF-8

MONGO_ID = '_id'
ID = 'id'
USOS_ID = 'usos_id'
USER_ID = 'user_id'
MOBILE_ID = 'mobile_id'
COURSE_ID = 'course_id'
COURSE_NAME = 'course_name'
TERM_ID = 'term_id'
TERMS_ORDER_KEY = 'order_key'
UNIT_ID = 'unit_id'
GROUP_ID = 'course_unit_id'
FRIEND_ID = 'friend_id'
PROGRAMME_ID = 'programme_id'
FACULTY_ID = 'fac_id'
FACULTY_NAME = 'name'
TT_STARTDATE = 'start_date'
COURSE_EDITIONS = 'course_editions'
CLASS_TYPE = 'class_type'
CLASS_TYPE_ID = 'classtype_id'
VALUE_DESCRIPTION = 'value_description'
VALUE_SYMBOL = 'value_symbol'
PHOTO_URL = 'photo_url'
PARTICIPANTS = 'participants'
LECTURERS = 'lecturers'
COORDINATORS = 'coordinators'
PICTURE = 'picture'
GRADES = 'grades'
SEARCH_QUERY = 'query'
SEARCH_ENDPOINT = 'endpoint'
NODE_ID = 'node_id'
USOS_USER_ID = 'usos_user_id'
EXAM_SESSION_NUMBER = 'exam_session_number'

EVENT_ENABLE = 'event_enable'
GOOGLE_CALLENDAR_ENABLE = 'google_callendar_enable'

FACEBOOK = 'facebook'
FACEBOOK_ID = 'id'
FACEBOOK_NAME = 'name'
FACEBOOK_EMAIL = 'email'
FACEBOOK_ACCESS_TOKEN = 'access_token'
FACEBOOK_SESSION_EXPIRES = 'session_expires'
FACEBOOK_PICTURE = 'picture'

GOOGLE = 'google'
GOOGLE_NAME = 'name'
GOOGLE_EMAIL = 'email'
GOOGLE_PICTURE = 'picture'
GOOGLE_ACCESS_TOKEN = 'access_token'
GOOGLE_EXPIRES_IN = 'expires_in'
GOOGLE_ID_TOKEN = 'id_token'
GOOGLE_TOKEN_TYPE = 'token_type'

CREATED_TIME = 'created_time'
UPDATE_TIME = 'update_time'
ACCESS_TOKEN_KEY = 'access_token_key'
ACCESS_TOKEN_SECRET = 'access_token_secret'
OAUTH_VERIFIER = 'oauth_verifier'

USOS_URL = 'url'
USOS_NAME = 'name'
USOS_LOGO = 'logo'
CONSUMER_KEY = 'consumer_key'
CONSUMER_SECRET = 'consumer_secret'

JOB_STATUS = 'status'
JOB_TYPE = 'type'
JOB_MESSAGE = 'message'
JOB_DATA = 'job_data'

USER_TYPE = 'user_type'
USER_CREATED = 'user_created'
USOS_PAIRED = 'usos_paired'
USER_NAME = 'name'
USER_EMAIL = 'email'
USER_PICTURE = 'picture'
USER_PASSWORD = 'password'
USER_EMAIL_CONFIRMED = 'email_confirmed'
USER_DEVICE_TYPE = 'device_type'
USER_DEVICE_ID = 'device_id'

USER_PRESENT_KEYS = (MOBILE_ID, USOS_ID, ACCESS_TOKEN_KEY, ACCESS_TOKEN_SECRET)

MOBI_TOKEN = 'mobi_token'

LECTURER_STATUS = 'staff_status'
LECTURER_STATUS_ACTIVE = 2

ALERT_MESSAGE = 'alert_message'
GRADE_FINAL = 'Końcowa'

FIELD_MESSAGE_FROM = 'from'
FIELD_MESSAGE_TYPE = 'typ'
FIELD_MESSAGE_TEXT = 'text'
ONESIGNAL_NOTIFICATION_RESULT = 'onesignal_result'

COOKIE_FIELDS = (ID, ACCESS_TOKEN_KEY, ACCESS_TOKEN_SECRET, USOS_ID, USOS_PAIRED, USER_EMAIL, USER_NAME, USER_PICTURE,
                 GOOGLE, FACEBOOK, USOS_USER_ID)

FILE_NAME = 'file_name'
FILE_SIZE = 'file_size'
FILE_STATUS = 'file_status'
FILE_CONTENT_TYPE = 'file_content_type'
FILE_CONTENT = 'file_content'
FILE_SCAN_RESULT = 'file_scan_result'
FILE_ID = 'file_id'
FILE_USER_INFO = 'user_info'
