# coding=UTF-8

USOSINSTANCES = [
    {'usos_id': 'DEMO',
     'name': 'The University of Wąchock - DEMO',
     'url': 'https://usosapps.demo.usos.edu.pl/',
     'logo': '/static/img/DEMO.jpeg',
     'consumer_key': 'FMmNufDTWNBxceDKwTED',
     'consumer_secret': '293pW5PrhKAFQ5kwJLYUxeFyNtUhPh2S4NYCTvjC',
     'contact': 'dsksysadm@adm.uw.edu.pl'
     },
    {'usos_id': 'UW',
     'name': 'Uniwersytet Warszawski',
     'url': 'https://usosapps.uw.edu.pl/',
     'logo': '/static/img/UW.jpeg',
     'consumer_key': 'KBt6uWPWUekUzFtNTyY9',
     'consumer_secret': 'Bm7wwuKSekhZKFs77GmP4vxHKgf4B7nFmSzUfWeG',
     'contact': 'dsksysadm@adm.uw.edu.pl'
     },
    {'usos_id': 'PS',
     'name': 'Politechnika Świętokrzystka',
     'url': 'https://api.usos.tu.kielce.pl/',
     'logo': '/static/img/PS.jpeg',
     'consumer_key': 'KjkcJxANGhWF8dxtjKkM',
     'consumer_secret': '9FZvfvmQSLePjw3V5k5guSfERr7eN8USPMHzHV6U',
     'contact': 'd.walczyk@tu.kielce.pl'
     },
    {'usos_id': 'PWSZ',
     'name': 'Państwowa Wyższa Szkoła Zawodowa w Elblągu',
     'url': 'https://usosapps.pwsz.elblag.pl/',
     'logo': '/static/img/PWSZ.jpeg',
     'consumer_key': '',
     'consumer_secret': '',
     'contact': 'l.grzybek@pwsz.elblag.pl, p.kwasniewski@pwsz.elblag.pl'
     },
    # {'usos_id': 'AMU',
    #  'name': 'Uniwersytet im. Adama Mickiewicza w Poznaniu',
    #  'url': 'https://api.usos.tu.kielce.pl/',
    #  'consumer_key': '',
    #  'consumer_secret': '',
    #  'contact': 'd.walczyk@tu.kielce.pl'
    #  },
    # {'usos_id': 'PB',
    #  'name': 'Politechnika Białostocka',
    #  'url': 'https://api.uci.pb.edu.pl/',
    #  'consumer_key': '',
    #  'consumer_secret': '',
    #  'contact': 'r.klim@uci.pb.edu.pl'
    #  },
    # {'usos_id': 'UJ',
    #  'name': 'Uniwersytet Jagieloński',
    #  'url': 'https://apps.usos.uj.edu.pl/',
    #  'consumer_key': '',
    #  'consumer_secret': '',
    #  'contact': 'michal.pysz@uj.edu.pl, michal.zabicki@uj.edu.pl'
    #  },
    # {'usos_id': 'AWF Katowice',
    #  'name': 'AWF im. Jerzego Kulczyka w Katowicach',
    #  'url': 'https://usosapps.awf.katowice.pl/',
    #  'consumer_key': '',
    #  'consumer_secret': '',
    #  'contact': 's.kwiatkowski@awf.katowice.pl, b.czerwinski@awf.katowice.pl'
    #  },
    # {'usos_id': 'UKW',
    #  'name': 'Uniwersytet Kazimierza Wielkiego w Bydgoszczy',
    #  'url': 'https://api.ukw.edu.pl/',
    #  'consumer_key': '',
    #  'consumer_secret': '',
    #  'contact': 'marekmac@ukw.edu.pl'
    #  },
]
