#!/bin/bash

SOURCE_DIRECTORY=/home/backup
TARGET_USER=u123777
TARGET_DIRECTORY=/backup
TARGET_SERVER=u123777.your-backup.de

scp ${SOURCE_DIRECTORY}/* ${TARGET_USER}@${TARGET_SERVER}:${TARGET_DIRECTORY}
